{% set version = "0.10.1" %}

package:
  name: r-evaluate
  version: {{ version }}

source:
  fn: evaluate_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/evaluate_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/evaluate/evaluate_{{ version }}.tar.gz
  sha256: c9a763895d3f460dbf87c43a6469e4b41a251a74477df8c5d7e7d2b66cdd1b1c 

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:  # [not win32]
  build:  # [not win32]
    - r-base  # [not win32]
    - r-stringr >=0.6.2  # [not win32]
  run:  # [not win32]
    - r-base  # [not win32]
    - r-stringr >=0.6.2  # [not win32]

test:
  commands:
    - R -e "library('evaluate')"  # [not win]
    - R -e \"library('evaluate')\"  # [win]

about:
  home: https://github.com/hadley/evaluate
  license: MIT
  license_file: LICENSE
  summary: 'Parsing and evaluation tools that make it easy to recreate the command line behaviour of R.'

extra:
  recipe-maintainers:
    - ocefpaf
