{% set version = '0.11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-evaluate
  version: {{ version|replace("-", "_") }}

source:
  fn: evaluate_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/evaluate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/evaluate/evaluate_{{ version }}.tar.gz
  sha256: b04805ffb56d82e2d5b044aa32de7e9ef4162ea619fd368f83e03dbd49631bcd

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-stringr >=0.6.2

  run:
    - r-base
    - r-stringr >=0.6.2

test:
  commands:
    - $R -e "library('evaluate')"           # [not win]
    - "\"%R%\" -e \"library('evaluate')\""  # [win]

about:
  home: https://github.com/r-lib/evaluate
  license: MIT
  summary: Parsing and evaluation tools that make it easy to recreate the command line behaviour
    of R.
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
