appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZhpKHdhAClY5RS9OhXYzt5kBHlanGF1c8FPBM+4303j/d6lZKAQ/6BilceQJZUO19/7vJ2TqCo99B80DeQOi7JsK25ABYL0c3/In/jJ4xC01K3YdSaEm6UyjzVUIrca1EXLu8rBhMwt1TOPhwhzog2ymUROc6+4hZING8AN4+DjhW5LJQiSuVaFazgaNy8y+02nXA1MEoQTLjmqg2RCH545CMNTmHPB+ygeyML+E5LD4/RimWrpYJtVqdLcEh5aNXjrY7CxVM3tEXIQr0IX4Wop/uxlcGcAuJwGQJCQK34UW0Y4iE59X/jILyP1pBXZyWpBEIPlv1DI83iRoWrM6H2Ci7zs0X49ZTnGQ0TPiXwyneTf7esj12hvJbLXfT0h0KJx3OKro+PreGwNmzCKUSQurpxcE36BxtVdjZeuSp68+arR2Y93Yzs0/fr93rbtPBznyqdV0Rs6RJA7FNfMSO/SmZBrZtdqvo2GTuO/6sQbpWLncnzyWqYaC+R2CGON5IHI8XDXAmTLpbl8+ykwMFIB/AwgyXUVp6TFXXhnQ1C3YibiC00hIPSjLdKIrWcicRfwZZj69uA9RBcELNcW4DRtLZ1vw9rYYh2AfMQVMONS+WmFaytZBPwj1sDJiEx3TRREkFdeESEHbv7CuZd1pxGrAEzbtGHQPRyzCY2kOooM=
conda_forge_output_validation: true
